# Generated by Django 6.0 on 2026-01-28 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete'), ('RESTORE', 'Restore'), ('CUSTOM', 'Custom')], max_length=20)),
                ('resource', models.CharField(max_length=120)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField()),
                ('beforeData', models.JSONField(blank=True, default=dict)),
                ('afterData', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(blank=True, max_length=120, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['resource', 'user_id', 'createdAt'], name='audit_log_resourc_1d8f3e_idx'), models.Index(fields=['action', 'createdAt'], name='audit_log_action_c6e62f_idx'), models.Index(fields=['createdBy', 'createdAt'], name='audit_log_created_ba008a_idx'), models.Index(fields=['origin', 'createdAt'], name='audit_log_origin_3ca73d_idx')],
            },
        ),
    ]
