# Generated by Django 6.0 on 2026-01-29 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_resourc_1d8f3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_action_c6e62f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_created_ba008a_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_origin_3ca73d_idx',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='updatedBy',
            new_name='updated_by',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource', 'user_id', 'created_at'], name='audit_log_resourc_78133f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_log_action_97df64_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_by', 'created_at'], name='audit_log_created_f4f052_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['origin', 'created_at'], name='audit_log_origin_9650c3_idx'),
        ),
    ]
