# Generated by Django 6.0 on 2026-04-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portugal2030Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domination', models.TextField()),
                ('classification', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('fund', models.CharField(max_length=255)),
                ('notice_publication_date', models.DateTimeField()),
                ('notice_start_date', models.DateTimeField()),
                ('notice_end_date', models.DateTimeField()),
                ('notice_updated_at', models.DateTimeField()),
                ('global_allocation', models.DecimalField(decimal_places=2, max_digits=100)),
                ('national_allocation', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('total_allocation', models.DecimalField(decimal_places=2, max_digits=100)),
                ('documents', models.TextField(blank=True)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portugal_2030_notices',
                'indexes': [models.Index(fields=['code', 'type'], name='port2030_code_type_idx')],
            },
        ),
    ]
